server:
  port: 9090

spring:
  application:
    name: Inditex-Service
  datasource:
    url: jdbc:h2:mem:inditexdb;INIT=runscript from 'classpath:db/init.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    currentSchema: inditex
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: inditex
  h2:
    console:
      enabled: true
      path: /h2-console
